name: fis_toplama
description: Fis Toplama - Android, iOS ve Web için fiş arşivleme ve 6'lı A4 PDF uygulaması.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  pdf: ^3.11.1
  printing: ^5.13.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
